### ISSUE TITLE
rdf_pg.ml Postgresql issues.

### ISSUE THREAD

**Issue by arkinjo** [zoggy/ocaml-rdf#11]
In rdf_pg.ml, 

line 62:
```OCaml
let quote_str s = "\"" ^ (String.escaped s) ^ "\"";;
```
-->
```OCaml
let quote_str s = "'" ^ (String.escaped s) ^ "'";;
```
Single quote (') rather than double quote ("). Or is this really necessary? Even
```OCaml
let quote_str s = String.escaped s;;
```
may be OK(?)

line 298:
```OCaml
 let query = "DELETE FROM "^nstable^" WHERE NAME=?" in
```
-->
```OCaml
 let query = "DELETE FROM "^nstable^" WHERE NAME=$1" in
```

"?" should be "$1", etc. Similarly,

line 301:
```OCaml
let query = "INSERT INTO "^nstable^" (iri, name) VALUES (?, ?)" in
```
-->
```OCaml
let query = "INSERT INTO "^nstable^" (iri, name) VALUES ($1, $2)" in
```
Sorry for the clumsy report. I'm not familiar with bug reporting...
Anyway, this is a great library. Thanks a lot!

**Comment by zoggy** [comment]
Regarding string escape: The string must be between " or ' to be handled as a string by Postgersql. Since ``String.escaped`` does not escape simple quotes but only double quotes, I escape the string and put it between double quotes. If I used simple quotes to delimit the string, I would have to escape simple quotes in the given string. ``String.escaped`` exists and is well tested, so it's simpler to use it.

**Comment by zoggy** [comment]
Regarding query parameters, this should indeed be $1, $2 and so on.  Thanks.

**Comment by arkinjo** [comment]
Thanks for the fix.
Regarding string escape, it seems you don't actually need to escape a string when you use it as a parameter for $1, $2, etc.
From http://www.postgresql.org/docs/9.4/static/libpq-exec.html
>The primary advantage of PQexecParams over PQexec is that parameter values can be separated from the command string, thus avoiding the need for tedious and error-prone quoting and escaping.

So, for example,
```OCaml
let rem_namespace g name =
  let params = [ quote_str name ] in
  ignore(exec_prepared g.g_dbd prepared_delete_namespace params)
```
can be simply
```OCaml
let rem_namespace g name =
  let params = [ name ] in
  ignore(exec_prepared g.g_dbd prepared_delete_namespace params)
```
i.e., without "quote_str".

**Comment by zoggy** [comment]
Ah, thanks. In fact, I was manually building a EXECUTE statement, handling string escaping, but there exists a exec_prepared method I can give not-escaped parameter, as you mention. I will simplify accordingly.

**Comment by zoggy** [comment]
Done. And I fixed a syntax error in a query. Looks like I did not test the PG backend very well. I added a test_pqsql test program.

**Comment by arkinjo** [comment]
Great! Thanks a lot.
