### ISSUE TITLE
Final backslash in literal string not getting escaped

### ISSUE THREAD

**Issue by juanchanco** [zoggy/ocaml-rdf#12]
In rdf_utf8.ml:257 the code checks that the current char isn't the last (to avoid an array out of bounds when checking s[i+1]), however, this mean if the backslash _is_ the last character, this case never fires and the output literal string ends with \" resulting in bad turtle. Changing tp "when (...) || i = len -1" fixes this.

For context, I have some data when the rdf object is a literal string indicating a delimiter used elsewhere, so the value is "\". There is also some messy data with stray key strokes, like "na\".

**Comment by zoggy** [comment]
Fixed in https://github.com/zoggy/ocaml-rdf/commit/7b718907404cb44b10617f7efbe0f612b850f186 . Thanks

**Comment by juanchanco** [comment]
Awesome, thanks! This greatly simplifies my code.
